// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"github.com/nicksnyder/go-i18n/v2/i18n"
)

// =============================================================================
// 🧊 ActionFlagDesc
//
// Cobra flag description for action flag
// =============================================================================

// ActionFlagDescTemplData Cobra flag description for action flag.
type ActionFlagDescTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for ActionFlagDescTemplData.
func (td ActionFlagDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "action-flag-description",
		Description: "Cobra flag description for action flag",
		Other:       "action denotes the executable or script function to invoke for each matching node, as defined in config",
	}
}

// =============================================================================
// 🧊 DryRunFlagDesc
//
// Cobra flag description for dry-run flag
// =============================================================================

// DryRunFlagDescTemplData Cobra flag description for dry-run flag.
type DryRunFlagDescTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for DryRunFlagDescTemplData.
func (td DryRunFlagDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "dry-run-flag-description",
		Description: "Cobra flag description for dry-run flag",
		Other:       "dry-run shows what would be executed without actually running the commands",
	}
}

// =============================================================================
// 🧊 IncludeHiddenFlagDesc
//
// Cobra flag description for include-hidden flag
// =============================================================================

// IncludeHiddenFlagDescTemplData Cobra flag description for include-hidden
// flag.
type IncludeHiddenFlagDescTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for IncludeHiddenFlagDescTemplData.
func (td IncludeHiddenFlagDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "include-hidden-flag-description",
		Description: "Cobra flag description for include-hidden flag",
		Other:       "include-hidden includes hidden files (dot files) and known metadata files in the traversal",
	}
}

// =============================================================================
// 🧊 PipelineFlagDesc
//
// Cobra flag description for pipeline flag
// =============================================================================

// PipelineFlagDescTemplData Cobra flag description for pipeline flag.
type PipelineFlagDescTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for PipelineFlagDescTemplData.
func (td PipelineFlagDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "pipeline-flag-description",
		Description: "Cobra flag description for pipeline flag",
		Other:       "pipeline denotes defines a sequence of actions to invoke for each matching node, as defined in config",
	}
}

// =============================================================================
// 🧊 ResumeFlagDesc
//
// Cobra flag description for resume flag
// =============================================================================

// ResumeFlagDescTemplData Cobra flag description for resume flag; values are
// staticso do not translate them.
type ResumeFlagDescTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for ResumeFlagDescTemplData.
func (td ResumeFlagDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "resume-flag-description",
		Description: "Cobra flag description for resume flag; values are staticso do not translate them",
		Other:       "resume denotes the strategy to use to continue a previously interrupted navigation: 'spawn' or 'ff'",
	}
}

// =============================================================================
// 🧊 SubscribeFlagDesc
//
// Cobra flag description for subscribe flag
// =============================================================================

// SubscribeFlagDescTemplData Cobra flag description for subscribe flag; values
// are static so do not translate them.
type SubscribeFlagDescTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for SubscribeFlagDescTemplData.
func (td SubscribeFlagDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "subscribe-flag-description",
		Description: "Cobra flag description for subscribe flag; values are static so do not translate them",
		Other:       "subscribe denotes the node types to visit: 'files', 'dirs' or 'all' (default)",
	}
}

// =============================================================================
// 🧊 ThemeFlagDesc
//
// Cobra flag description for theme flag
// =============================================================================

// ThemeFlagDescTemplData Cobra flag description for theme flag.
type ThemeFlagDescTemplData struct {
	agenorTemplData
	// Path The path to the colour themes file
	Path string
}

// Message returns the i18n message for ThemeFlagDescTemplData.
func (td ThemeFlagDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "theme-flag-description",
		Description: "Cobra flag description for theme flag",
		Other:       "theme denotes colour theme selection (default: system), loaded from '{{.Path}}'",
	}
}

// NewThemeFlagDescTemplData creates a new ThemeFlagDescTemplData.
func NewThemeFlagDescTemplData(path string) ThemeFlagDescTemplData {
	return ThemeFlagDescTemplData{
		agenorTemplData: agenorTemplData{},
		Path:            path,
	}
}

// =============================================================================
// 🧊 TuiFlagDesc
//
// Cobra flag description for TUI flag
// =============================================================================

// TuiFlagDescTemplData Cobra flag description for TUI flag.
type TuiFlagDescTemplData struct {
	agenorTemplData
}

// Message returns the i18n message for TuiFlagDescTemplData.
func (td TuiFlagDescTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "tui-flag-description",
		Description: "Cobra flag description for TUI flag",
		Other:       "tui denotes what view to use (default: linear)",
	}
}
