// Code generated by lingo. DO NOT EDIT.
// Re-generate by running: go generate

package locale

import (
	"fmt"
	"github.com/nicksnyder/go-i18n/v2/i18n"
	"github.com/snivilised/li18ngo"
)

// =============================================================================
// ❌ PortholeViewNotSupportedBySprint
//
// Error returned when porthole view is requested via the sprint command
// =============================================================================

// PortholeViewNotSupportedBySprintErrorTemplData Porthole view not supported by
// sprint command error.
type PortholeViewNotSupportedBySprintErrorTemplData struct {
	agenorTemplData
	// Wrapped is the string representation of the wrapped error,
	// used for go-i18n template interpolation via {{ .Wrapped }}.
	Wrapped string
}

// Message creates a new i18n message using the template data.
func (td PortholeViewNotSupportedBySprintErrorTemplData) Message() *i18n.Message {
	return &i18n.Message{
		ID:          "porthole-view-not-supported-by-sprint.static-error",
		Description: "Porthole view not supported by sprint command error",
		Other:       "{{.Wrapped}}",
	}
}

// PortholeViewNotSupportedBySprintError Porthole view not supported by sprint
// command error.
type PortholeViewNotSupportedBySprintError struct {
	li18ngo.LocalisableError
	wrapped error
}

// Error returns the combined wrapped and localised error message.
func (e PortholeViewNotSupportedBySprintError) Error() string {
	return fmt.Sprintf("%v, %v", e.wrapped.Error(), li18ngo.Text(e.LocalisableError.Data))
}

// Unwrap returns the wrapped error.
func (e PortholeViewNotSupportedBySprintError) Unwrap() error {
	return e.wrapped
}

// NewPortholeViewNotSupportedBySprintError creates a new
// PortholeViewNotSupportedBySprintError wrapping wrapped.
func NewPortholeViewNotSupportedBySprintError(wrapped error) error {
	return &PortholeViewNotSupportedBySprintError{
		LocalisableError: li18ngo.LocalisableError{
			Data: PortholeViewNotSupportedBySprintErrorTemplData{Wrapped: wrapped.Error()},
		},
		wrapped: wrapped,
	}
}
