// Code generated by "stringer -type=CurveKind -linecomment -trimprefix=CurveKind -output curve-kind-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CurveKindLinear-0]
	_ = x[CurveKindSine-1]
	_ = x[CurveKindQuadraticIn-2]
	_ = x[CurveKindQuadraticOut-3]
	_ = x[CurveKindCubic-4]
}

const _CurveKind_name = "linearsinequadratic-inquadratic-outcubic"

var _CurveKind_index = [...]uint8{0, 6, 10, 22, 35, 40}

func (i CurveKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CurveKind_index)-1 {
		return "CurveKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CurveKind_name[_CurveKind_index[idx]:_CurveKind_index[idx+1]]
}
