// Code generated by "stringer -type=EasingKind -linecomment -trimprefix=EasingKind -output easing-kind-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EasingKindUniform-0]
	_ = x[EasingKindEaseIn-1]
	_ = x[EasingKindEaseOut-2]
	_ = x[EasingKindEaseInOut-3]
}

const _EasingKind_name = "uniformease-inease-outease-in-out"

var _EasingKind_index = [...]uint8{0, 7, 14, 22, 33}

func (i EasingKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EasingKind_index)-1 {
		return "EasingKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EasingKind_name[_EasingKind_index[idx]:_EasingKind_index[idx+1]]
}
