// Code generated by "stringer -type=NavigationKind -linecomment -trimprefix=NavigationKind -output navigation-kind-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NavigationKindPrime-0]
	_ = x[NavigationKindResume-1]
}

const _NavigationKind_name = "primeresume"

var _NavigationKind_index = [...]uint8{0, 5, 11}

func (i NavigationKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NavigationKind_index)-1 {
		return "NavigationKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NavigationKind_name[_NavigationKind_index[idx]:_NavigationKind_index[idx+1]]
}
