// Code generated by "stringer -type=ViewKind -linecomment -trimprefix=ViewKind -output view-kind-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ViewKindLinear-0]
	_ = x[ViewKindPorthole-1]
	_ = x[ViewKindHighway-2]
}

const _ViewKind_name = "linearportholehighway"

var _ViewKind_index = [...]uint8{0, 6, 14, 21}

func (i ViewKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ViewKind_index)-1 {
		return "ViewKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ViewKind_name[_ViewKind_index[idx]:_ViewKind_index[idx+1]]
}
