// Code generated by "stringer -type=WorkerState -linecomment -trimprefix=WorkerState -output worker-state-en-auto.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WorkerStateUndefined-0]
	_ = x[WorkerStateIdle-1]
	_ = x[WorkerStateWorking-2]
}

const _WorkerState_name = "undefinedidleworking"

var _WorkerState_index = [...]uint8{0, 9, 13, 20}

func (i WorkerState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_WorkerState_index)-1 {
		return "WorkerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WorkerState_name[_WorkerState_index[idx]:_WorkerState_index[idx+1]]
}
